### ISSUE TITLE
ass

### ISSUE THREAD

**Issue by siphiuel** [siphiuel/ob-test1#176]

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0x09f76fce0b1093b6ffb7570e8f9b668ef80a3cd7fa7385a5916070f9c796463f](https://ropsten.etherscan.io/tx/0x09f76fce0b1093b6ffb7570e8f9b668ef80a3cd7fa7385a5916070f9c796463f)
