### ISSUE TITLE
qwe

### ISSUE THREAD

**Issue by siphiuel** [siphiuel/ob-test1#179]

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0xb3a51ce580a7e18da842cbc19250ebf990205ab2225ea3f74389aec6ba17f493](https://ropsten.etherscan.io/tx/0xb3a51ce580a7e18da842cbc19250ebf990205ab2225ea3f74389aec6ba17f493)
