### ISSUE TITLE
test tokens

### ISSUE THREAD

**Issue by siphiuel** [siphiuel/ob-test1#42]

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0x23c5357ede2872c627afbdda8974b3c90061ce7ff382d593e0ffedf2998a92bb](https://ropsten.etherscan.io/tx/0x23c5357ede2872c627afbdda8974b3c90061ce7ff382d593e0ffedf2998a92bb)
