### ISSUE TITLE
new_comment

### ISSUE THREAD

**Issue by siphiuel** [siphiuel/ob-test1#43]

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0x2ca0cb01f4a99fdabb4702be612f0d643c3aab80f437e993f6f5433475d042f0](https://ropsten.etherscan.io/tx/0x2ca0cb01f4a99fdabb4702be612f0d643c3aab80f437e993f6f5433475d042f0)

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0x85c7233b518fcdcf5b3207209325335d9981dd19b4498b55680a50a2cfa5bbd9](https://ropsten.etherscan.io/tx/0x85c7233b518fcdcf5b3207209325335d9981dd19b4498b55680a50a2cfa5bbd9)
