### ISSUE TITLE
Test-multi-claims

### ISSUE THREAD

**Issue by siphiuel** [siphiuel/ob-test1#46]

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0xf9e02c40732615efe3c95bf985286450ac265b5fea5a84d4084c7bb3d7a0692a](https://ropsten.etherscan.io/tx/0xf9e02c40732615efe3c95bf985286450ac265b5fea5a84d4084c7bb3d7a0692a)
