### ISSUE TITLE
test-readd

### ISSUE THREAD

**Issue by siphiuel** [siphiuel/ob-test1#49]

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0x42f22f817fc1aef8c8c503afb27cc8b524480fb9ae49cc2d4adb45dbbac9e8ff](https://ropsten.etherscan.io/tx/0x42f22f817fc1aef8c8c503afb27cc8b524480fb9ae49cc2d4adb45dbbac9e8ff)
