### ISSUE TITLE
asf

### ISSUE THREAD

**Issue by siphiuel** [siphiuel/ob-test1#52]

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0x66482aee6ee63bf5f0923ba58f3a343f7b5bad4836dc842589f7ad8fd0342c81](https://ropsten.etherscan.io/tx/0x66482aee6ee63bf5f0923ba58f3a343f7b5bad4836dc842589f7ad8fd0342c81)
