### ISSUE TITLE
asdf

### ISSUE THREAD

**Issue by siphiuel** [siphiuel/ob-test1#58]

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0x5091b8713f5ab2eb6d85727ec74718dba842558bfb54e9a5d3d0a4d57515d833](https://ropsten.etherscan.io/tx/0x5091b8713f5ab2eb6d85727ec74718dba842558bfb54e9a5d3d0a4d57515d833)
