### ISSUE TITLE
abc

### ISSUE THREAD

**Issue by siphiuel** [siphiuel/ob-test1#60]

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0xd02cc9b18eb8b3feee34c04c38486a64d3a12cde8581090796087cb90699186c](https://ropsten.etherscan.io/tx/0xd02cc9b18eb8b3feee34c04c38486a64d3a12cde8581090796087cb90699186c)
